### ISSUE TITLE
Copy button

### ISSUE THREAD

**Issue by jens-klenke** [mca91/OEK_ARE#4]
Copy Button auch für Markdown code. 

aktuell funktionieren beide einzeln aber wir bräuchten die nach Möglichkeit kombinieret. 
var allCodeBlocksElements = $( ".r");
var allCodeBlocksElements = $( ".markdown");

hatte sowas wie 

var allCodeBlocksElements = $( ".r  | .markdown");

ausprobiert

**Comment by mca91** [comment]
Wie besprochen mal das hier ausprobieren und ggf. unseren Button ersetzen:

https://github.com/gadenbuie/xaringanExtra

**Comment by mca91** [comment]
Close wg. https://github.com/mca91/OEK_ARE/commit/7aa792c28c30a5aa7d955409d510806326aba1d5  :)
